### Matrix Operations

In [19]:
import numpy as np

In [20]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.ones((5,3)) ## By default in float32/64bit

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
a=np.arange(1,7)
a

array([1, 2, 3, 4, 5, 6])

In [23]:
a[:3]=1
a ## assigning same value to multiple indices

array([1, 1, 1, 4, 5, 6])

In [24]:
b=np.zeros((2,2))
b[0,0]=1
b[0,1]=2
b[1,1]=4

### ARRAY OPERATIONS


In [25]:
b+2

array([[3., 4.],
       [2., 6.]])

In [26]:
2*b

array([[2., 4.],
       [0., 8.]])

In [27]:
b**2

array([[ 1.,  4.],
       [ 0., 16.]])

In [28]:
sum(b) ## builtin default python functions give vector sum 

array([1., 6.])

In [29]:
b.sum() ## numpy sum functions gives other result

7.0

In [34]:
b.sum(axis=0).shape


(2,)

In [35]:
b.sum(axis=1).shape

(2,)

In [32]:
b=np.array([[1,2],[3,4]])
d=np.array([[3,4],[5,6]])

In [33]:
print(b)
print(d)

[[1 2]
 [3 4]]
[[3 4]
 [5 6]]


In [36]:
b+d

array([[ 4,  6],
       [ 8, 10]])

In [37]:
b*d ## What operation is this?
#3 element wise multiplication

array([[ 3,  8],
       [15, 24]])

In [38]:
b.dot(d) ##Matrix Multiplication row and column wise

array([[13, 16],
       [29, 36]])

In [39]:
d.dot(b)

array([[15, 22],
       [23, 34]])

In [40]:
b**d

array([[   1,   16],
       [ 243, 4096]])

In [42]:
b

array([[1, 2],
       [3, 4]])

In [41]:
b.T ## Transpose

array([[1, 3],
       [2, 4]])

In [46]:
a.shape


(6,)

In [48]:
a.T.shape ### Transpose does not affect rank 1 tensor

(6,)

In [50]:
a.reshape(6,1).T.shape

(1, 6)

In [ ]:
a

In [44]:
## Numpy has broadcasting and mappung functions
print(np.sqrt(36))

x=[1,4,9,16]
np.sqrt(x)

6.0


array([1., 2., 3., 4.])

In [52]:
# checking conditions
x=np.array([1,2,4,5,9,3])
y=np.array([0,2,3,1,2,3])

In [53]:
x>3

array([False, False,  True,  True,  True, False])

In [55]:
x>y

array([ True, False,  True,  True,  True, False])

### Misc Operations with Numpy

In [56]:
import math
def basic_sigmoid(x):
    """ 
    
    Compute Sigmoid of x
    Arguemnts:
    x---A Scalar
    Return:
    s--sigmoid(x)

    """
    s=1./(1.+math.e**(-x))

    return s

In [57]:
basic_sigmoid(-1)

0.2689414213699951

In [63]:
basic_sigmoid(0)

0.5

In [65]:
x=[-1,0,3]
basic_sigmoid(x) ## Why?...minus of list is nothing

TypeError: bad operand type for unary -: 'list'

In [66]:
x=np.array(x)
basic_sigmoid(x)

array([0.26894142, 0.5       , 0.95257413])