In [9]:
%matplotlib inline


In [4]:
import numpy as np

np.random.seed(40)


### Basics Of Matrices


In [5]:
x=np.array([1,4,3])
x

array([1, 4, 3])

In [17]:
y=np.array([[1,4,3],
            [9,2,7]])

In [18]:
print(x.shape)

(3,)


In [19]:
y.shape

(2, 3)

In [20]:
z=np.array([[1,4,3]]) ### What is the difference from x
z

array([[1, 4, 3]])

In [21]:
z.shape 

(1, 3)

In [23]:
k=np.array([[1],[4],[3]])
k

array([[1],
       [4],
       [3]])

In [24]:
k.shape

(3, 1)

In [31]:
h=np.arange(1,2000,1)
h[:10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
h.shape ##1999 due to zero index

(1999,)

In [28]:
np.arange(0.5,10,1).shape

(10,)

In [34]:
np.arange(0.5,10,1).reshape(5,2)

array([[0.5, 1.5],
       [2.5, 3.5],
       [4.5, 5.5],
       [6.5, 7.5],
       [8.5, 9.5]])

In [35]:
np.arange(0.5,10,1).shape

(10,)

In [40]:
np.arange(0.5,10,1).reshape(5,2)


array([[0.5, 1.5],
       [2.5, 3.5],
       [4.5, 5.5],
       [6.5, 7.5],
       [8.5, 9.5]])

In [41]:
# Evenly spaced but we donot know the step size
np.linspace(3,9,10)


array([3.        , 3.66666667, 4.33333333, 5.        , 5.66666667,
       6.33333333, 7.        , 7.66666667, 8.33333333, 9.        ])

In [42]:
print(x)

[1 4 3]
